runtime: php55
api_version: 1
handlers: 
- url: /index
  script: index.php
- url: /process
  script: process.php
- url: /delete
  script: deleteUser.php 
- url: /edit
  script: formEdit.php 
- url: /update
  script: updateUser.php 
- url: /.*
  script: index.php

